suggestion:
  name: 饮料测评建议
  description: 用户推荐的饮品测评建议
  labels: ["suggestion"]
  title: "测评建议：{{ brand }} - {{ drink }}"
  body:
    - type: input
      id: brand
      attributes:
        label: 品牌
        description: 饮料品牌名称
        placeholder: 例如：茶月山
        required: true
    - type: input
      id: drink
      attributes:
        label: 饮品名称
        description: 具体饮品名称
        placeholder: 例如：汕头油柑茶
        required: true
    - type: input
      id: request
      attributes:
        label: 推荐规格
        description: 甜度/冰量等要求
    - type: textarea
      id: reason
      attributes:
        label: 推荐理由
        description: 为什么推荐这款饮品
